import type { Locale } from "./i18n";
const en = {
  title: "Messenger", close: "Close chat", loading: "Opening encrypted chat…", setup: "Enable encrypted chat", create: "Enable chat with account recovery",
  explanation: "Messages are encrypted on your device. In phase 1, recovery material is stored separately in Keycloak so a new browser can restore your chat after sign-in. Privileged operators or someone who takes over your account could also recover it. Your diary is not affected.",
  restore: "Unlock existing chat", code: "Existing recovery code", unlock: "Unlock on this device", migrate: "Enable account recovery", migrationConsent: "I want Keycloak to store recovery material for this existing chat and understand who could recover it.",
  legacy: "Account recovery is not enabled for this chat", legacyExplanation: "This chat still uses its original recovery code. You can unlock it on this device without changing that, or explicitly enable account recovery below.",
  memory: "This browser cannot save chat keys. After closing chat, sign-in and Keycloak account recovery will be needed again.",
  legacyMemory: "This browser cannot save chat keys. Keep your original recovery code: closing chat will lock it again.",
  unavailable: "Account recovery is currently unavailable. No new chat keys will be created. Try again later.", unavailableLocal: "Account recovery is unavailable. This device can still use its saved chat keys; a new browser cannot currently restore them.", retryRecovery: "Try opening chat again", retrySetup: "Retry chat activation",
  pending: "Your friend has not enabled encrypted chat yet.", error: "Chat could not be opened. Try again; for an existing manual backup, check the recovery code.",
  denied: "This conversation is no longer available.", changed: "The chat key does not match. Messages are locked; verify the identity before continuing.",
  safety: "Safety code", compare: "Compare this code with your friend in person or through a trusted channel. Matching codes verify your chat keys, not who is using the account.",
  verified: "Codes match", unverified: "Keys not independently verified", verifiedLabel: "Codes compared on this device", send: "Send", message: "Message", empty: "No messages yet.", older: "Older messages", retry: "Retry encrypted message", failed: "Message not sent. Your draft stays here while this chat is open.",
  privacy: "Phase 1: encrypted messages with account recovery, not protection against privileged operators. Text only · Confirmed friends · No notification previews.", legacyPrivacy: "This chat still uses its original manual backup. Account recovery has not been enabled. Text only · Confirmed friends · No notification previews.", unavailablePrivacy: "Encrypted messages · Account recovery unavailable · Confirmed friends · No notification previews.", blocked: "Block contact", blockConfirm: "Block this contact and close the conversation?", waiting: "Working…"
};
type Texts = typeof en;
const de: Texts = {
  title: "Messenger", close: "Chat schließen", loading: "Verschlüsselter Chat wird geöffnet…", setup: "Verschlüsselten Chat aktivieren", create: "Chat mit Kontowiederherstellung aktivieren",
  explanation: "Nachrichten werden auf deinem Gerät verschlüsselt. In Phase 1 liegt das Wiederherstellungsmaterial getrennt in Keycloak, damit ein neuer Browser deinen Chat nach der Anmeldung wiederherstellen kann. Privilegierte Betreiber oder jemand, der dein Konto übernimmt, könnten ihn ebenfalls wiederherstellen. Dein Tagebuch bleibt unverändert.",
  restore: "Bestehenden Chat entsperren", code: "Bisheriger Wiederherstellungscode", unlock: "Auf diesem Gerät entsperren", migrate: "Kontowiederherstellung aktivieren", migrationConsent: "Ich möchte das Wiederherstellungsmaterial dieses bestehenden Chats in Keycloak speichern und weiß, wer ihn dadurch wiederherstellen könnte.",
  legacy: "Kontowiederherstellung ist für diesen Chat noch nicht aktiviert", legacyExplanation: "Dieser Chat nutzt noch seinen bisherigen Wiederherstellungscode. Du kannst ihn nur auf diesem Gerät entsperren oder unten ausdrücklich die Kontowiederherstellung aktivieren.",
  memory: "Dieser Browser kann Chat-Schlüssel nicht speichern. Nach dem Schließen sind die Anmeldung und die Kontowiederherstellung über Keycloak erneut nötig.",
  legacyMemory: "Dieser Browser kann Chat-Schlüssel nicht speichern. Bewahre deinen bisherigen Wiederherstellungscode auf: Nach dem Schließen ist der Chat wieder gesperrt.",
  unavailable: "Die Kontowiederherstellung ist gerade nicht verfügbar. Es werden keine neuen Chat-Schlüssel erstellt. Versuche es später erneut.", unavailableLocal: "Die Kontowiederherstellung ist nicht verfügbar. Dieses Gerät kann seine gespeicherten Chat-Schlüssel weiter nutzen; ein neuer Browser kann sie gerade nicht wiederherstellen.", retryRecovery: "Chat erneut öffnen", retrySetup: "Chat-Aktivierung erneut versuchen",
  pending: "Dein Freund hat den verschlüsselten Chat noch nicht aktiviert.", error: "Der Chat konnte nicht geöffnet werden. Versuche es erneut; prüfe bei einer bisherigen manuellen Sicherung auch den Wiederherstellungscode.",
  denied: "Dieser Chat ist nicht mehr verfügbar.", changed: "Der Chat-Schlüssel stimmt nicht überein. Nachrichten bleiben gesperrt, bis die Identität geklärt ist.",
  safety: "Sicherheitscode", compare: "Vergleiche diesen Code persönlich oder über einen vertrauten Weg mit deinem Freund. Gleiche Codes bestätigen eure Chat-Schlüssel, nicht wer das Konto gerade benutzt.",
  verified: "Codes stimmen überein", unverified: "Schlüssel noch nicht unabhängig geprüft", verifiedLabel: "Codes auf diesem Gerät verglichen", send: "Senden", message: "Nachricht", empty: "Noch keine Nachrichten.", older: "Ältere Nachrichten", retry: "Verschlüsselte Nachricht erneut senden", failed: "Nachricht nicht gesendet. Dein Entwurf bleibt erhalten, solange dieser Chat geöffnet ist.",
  privacy: "Phase 1: verschlüsselte Nachrichten mit Kontowiederherstellung, kein Schutz vor privilegierten Betreibern. Nur Text · Bestätigte Freunde · Keine Nachrichtenvorschau.", legacyPrivacy: "Dieser Chat nutzt noch seine bisherige manuelle Sicherung. Kontowiederherstellung ist nicht aktiviert. Nur Text · Bestätigte Freunde · Keine Nachrichtenvorschau.", unavailablePrivacy: "Verschlüsselte Nachrichten · Kontowiederherstellung nicht verfügbar · Bestätigte Freunde · Keine Nachrichtenvorschau.", blocked: "Kontakt blockieren", blockConfirm: "Diesen Kontakt blockieren und den Chat schließen?", waiting: "Einen Moment…"
};
const fr: Texts = {
  title: "Messagerie", close: "Fermer", loading: "Ouverture du chat chiffré…", setup: "Activer le chat chiffré", create: "Activer le chat avec récupération du compte",
  explanation: "Les messages sont chiffrés sur votre appareil. En phase 1, les données de récupération sont conservées séparément dans Keycloak : un nouveau navigateur peut restaurer le chat après connexion. Des opérateurs privilégiés ou une personne ayant pris le contrôle de votre compte pourraient aussi le restaurer. Votre journal reste inchangé.",
  restore: "Déverrouiller le chat existant", code: "Ancien code de récupération", unlock: "Déverrouiller sur cet appareil", migrate: "Activer la récupération du compte", migrationConsent: "Je souhaite conserver les données de récupération de ce chat dans Keycloak et je comprends qui pourrait le restaurer.",
  legacy: "La récupération du compte n’est pas activée pour ce chat", legacyExplanation: "Ce chat utilise encore son ancien code de récupération. Vous pouvez le déverrouiller uniquement sur cet appareil ou activer explicitement la récupération du compte ci-dessous.",
  memory: "Ce navigateur ne peut pas conserver les clés. Après fermeture du chat, une connexion et la récupération via Keycloak seront à nouveau nécessaires.",
  legacyMemory: "Ce navigateur ne peut pas conserver les clés. Gardez votre ancien code : le chat sera verrouillé après fermeture.",
  unavailable: "La récupération du compte est indisponible. Aucune nouvelle clé ne sera créée. Réessayez plus tard.", unavailableLocal: "La récupération du compte est indisponible. Cet appareil peut utiliser ses clés enregistrées ; un nouveau navigateur ne peut pas les restaurer actuellement.", retryRecovery: "Réessayer d’ouvrir le chat", retrySetup: "Réessayer l’activation du chat",
  pending: "Votre ami n’a pas encore activé le chat chiffré.", error: "Impossible d’ouvrir le chat. Réessayez ; pour une ancienne sauvegarde manuelle, vérifiez aussi le code.", denied: "Cette conversation n’est plus disponible.", changed: "La clé du chat ne correspond pas. Vérifiez l’identité avant de continuer.",
  safety: "Code de sécurité", compare: "Comparez ce code avec votre ami en personne ou par un canal de confiance. Un code identique confirme les clés, pas l’identité de la personne utilisant le compte.",
  verified: "Les codes correspondent", unverified: "Clés non vérifiées indépendamment", verifiedLabel: "Codes comparés sur cet appareil", send: "Envoyer", message: "Message", empty: "Aucun message.", older: "Messages précédents", retry: "Réessayer le message chiffré", failed: "Message non envoyé. Le brouillon reste disponible tant que ce chat est ouvert.",
  privacy: "Phase 1 : messages chiffrés avec récupération du compte, sans protection contre les opérateurs privilégiés. Texte uniquement · Amis confirmés · Aucun aperçu.", legacyPrivacy: "Ce chat utilise encore sa sauvegarde manuelle d’origine. La récupération du compte n’est pas activée. Texte uniquement · Amis confirmés · Aucun aperçu.", unavailablePrivacy: "Messages chiffrés · Récupération du compte indisponible · Amis confirmés · Aucun aperçu.", blocked: "Bloquer le contact", blockConfirm: "Bloquer ce contact et fermer la conversation ?", waiting: "Patientez…"
};
const es: Texts = {
  title: "Mensajería", close: "Cerrar chat", loading: "Abriendo chat cifrado…", setup: "Activar chat cifrado", create: "Activar chat con recuperación de cuenta",
  explanation: "Los mensajes se cifran en tu dispositivo. En la fase 1, los datos de recuperación se guardan por separado en Keycloak para que un navegador nuevo restaure el chat tras iniciar sesión. Los operadores con privilegios o alguien que tome el control de tu cuenta también podrían restaurarlo. Tu diario no cambia.",
  restore: "Desbloquear el chat existente", code: "Código de recuperación anterior", unlock: "Desbloquear en este dispositivo", migrate: "Activar recuperación de cuenta", migrationConsent: "Quiero guardar en Keycloak los datos de recuperación de este chat y entiendo quién podría restaurarlo.",
  legacy: "La recuperación de cuenta no está activada para este chat", legacyExplanation: "Este chat aún usa su código de recuperación anterior. Puedes desbloquearlo solo en este dispositivo o activar expresamente la recuperación de cuenta a continuación.",
  memory: "Este navegador no puede guardar las claves. Al cerrar el chat, necesitarás iniciar sesión y recuperarlo mediante Keycloak de nuevo.",
  legacyMemory: "Este navegador no puede guardar las claves. Conserva tu código anterior: el chat quedará bloqueado al cerrarlo.",
  unavailable: "La recuperación de cuenta no está disponible. No se crearán claves nuevas. Inténtalo más tarde.", unavailableLocal: "La recuperación de cuenta no está disponible. Este dispositivo puede usar sus claves guardadas; un navegador nuevo no puede restaurarlas por ahora.", retryRecovery: "Volver a abrir el chat", retrySetup: "Reintentar la activación del chat",
  pending: "Tu amigo aún no ha activado el chat cifrado.", error: "No se pudo abrir el chat. Inténtalo de nuevo; si usas una copia manual anterior, comprueba también el código.", denied: "Esta conversación ya no está disponible.", changed: "La clave del chat no coincide. Verifica la identidad antes de continuar.",
  safety: "Código de seguridad", compare: "Compara este código con tu amigo en persona o por un canal de confianza. Los códigos iguales confirman las claves, no quién usa la cuenta.",
  verified: "Los códigos coinciden", unverified: "Claves sin verificar independientemente", verifiedLabel: "Códigos comparados en este dispositivo", send: "Enviar", message: "Mensaje", empty: "Aún no hay mensajes.", older: "Mensajes anteriores", retry: "Reintentar mensaje cifrado", failed: "Mensaje no enviado. El borrador se conserva mientras este chat esté abierto.",
  privacy: "Fase 1: mensajes cifrados con recuperación de cuenta, sin protección frente a operadores con privilegios. Solo texto · Amigos confirmados · Sin vistas previas.", legacyPrivacy: "Este chat aún usa su copia manual original. La recuperación de cuenta no está activada. Solo texto · Amigos confirmados · Sin vistas previas.", unavailablePrivacy: "Mensajes cifrados · Recuperación de cuenta no disponible · Amigos confirmados · Sin vistas previas.", blocked: "Bloquear contacto", blockConfirm: "¿Bloquear este contacto y cerrar la conversación?", waiting: "Un momento…"
};
export const chatMessages: Record<Locale, Texts> = { en, de, fr, es };
